language: java

jdk: openjdk11

sudo: true

services:
  - docker

before_install:
  - chmod +x mvnw
  
script: mvn clean verify

branches:
  only:
    - main
    - master
    - stable
    - develop
    - release
  except:
    - feature

deploy:
  provider: script
  script: bash docker_build
  on:
    branch: main

