language: java

jdk: openjdk11

sudo: true

before_install:
  - chmod +x mvnw
  
script: mvn clean verify

branches:
  only:
    - main
    - master
    - stable
    - develop
    - release
  except:
    - feature
