language: java

jdk: openjdk11

sudo: true

services:
  - docker

before_install:
  - chmod +x mvnw

branches:
  only:
    - main
    - master
    - stable
    - develop
    - release
  except:
    - feature

stages:
    - name: build
      script: mvn clean install

after_success: bash docker_build


