language: java

jdk: openjdk11

sudo: true

services:
  - docker

before_install:
  - chmod +x mvnw
  - AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli

branches:
  only:
    - main
    - master
    - stable
    - develop
    - release
  except:
    - feature

stages:
    - name: build
      script: mvn clean install

after_success: bash dockerbuild

deploy:
  provider: script
  script: bash aksdeploy



