#!/bin/bash

echo "---------- build image and deploy ----------"
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
docker build -t demoapp .
docker tag demoapp $DOCKER_USERNAME/demoapp
docker push $DOCKER_USERNAME/demoapp
