global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'prometheusJob'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] #Servidor prometheus
  - job_name: 'spring-monitoring-app-demo'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['demo-app:8080'] #Servidor da minha aplicação