server:
  port: 8080
api:
  version: @project.version@
spring:
  application:
    name: poc-demo
  banner:
    location: classpath:custom-banner.txt
#  data:
#    mongodb:
#      authentication-database: admin
#      host: localhost
#      port: 27017
#      database: demo-app-db
#      username: root
#      password: example
#  cache:
#    caffeine:
#      spec: expireAfterAccess=30s
#    type: redis
#    redis:
#      key-prefix: demo-app-
#      cache-null-values: false
#      time-to-live: 36000
#  redis:
#    host: localhost
#    port: 6379
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
springdoc:
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    operationsSorter: method
openapi:
  info:
    version: @project.version@
    description: API rest demo with spring
    title: API DEMO
    email: williamfincatti.dasila@gmail.com
tmdb:
  api:
    key: ${TMDB_API_KEY}
  base:
    url: https://api.themoviedb.org/3