spring:
  data:
    mongodb:
      authentication-database: admin
      host: mongo-db
      port: 27017
      database: demo-app-db
      username: root
      password: example
  redis:
    host: redis
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"
tmdb:
  api:
    key: ${TMDB_API_KEY}
  base:
    url: https://api.themoviedb.org/3