apiVersion: v1
kind: Namespace
metadata:
  name: demos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demos
  name: demo-app-deployment
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: wlmfincatti/demoapp
        resources:
          limits:
            memory:  "512Mi"
            cpu: "750m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: demos
  name: demo-app-svc
spec:
  type: LoadBalancer
  selector:
    app:  demo-app
  ports:
  - 
    port: 8080
    targetPort: 8080

    

